"""add conversation call state

Revision ID: c5662290beb3
Revises: a4a075a39043
Create Date: 2026-07-16 17:31:16.032510+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c5662290beb3'
down_revision: Union[str, None] = 'a4a075a39043'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calls', sa.Column('language', sa.String(length=32), nullable=True))
    op.add_column('calls', sa.Column('current_intent', sa.String(length=64), nullable=True))
    op.add_column('calls', sa.Column('identified_patient_id', sa.UUID(), nullable=True))
    op.add_column('calls', sa.Column('selected_branch_id', sa.UUID(), nullable=True))
    op.add_column('calls', sa.Column('selected_practitioner_id', sa.UUID(), nullable=True))
    op.add_column('calls', sa.Column('selected_appointment_type_id', sa.UUID(), nullable=True))
    op.add_column('calls', sa.Column('last_availability_search', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('calls', sa.Column('pending_confirmation', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('calls', sa.Column('conversation_summary', sa.Text(), nullable=True))
    op.add_column('calls', sa.Column('last_tool_called', sa.String(length=64), nullable=True))
    op.add_column('calls', sa.Column('last_updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_calls_identified_patient_id'), 'calls', ['identified_patient_id'], unique=False)
    op.create_foreign_key(
        'fk_calls_selected_branch_id_branches',
        'calls',
        'branches',
        ['selected_branch_id'],
        ['id'],
        ondelete='SET NULL',
    )
    op.create_foreign_key(
        'fk_calls_selected_appointment_type_id_appointment_types',
        'calls',
        'appointment_types',
        ['selected_appointment_type_id'],
        ['id'],
        ondelete='SET NULL',
    )
    op.create_foreign_key(
        'fk_calls_selected_practitioner_id_practitioners',
        'calls',
        'practitioners',
        ['selected_practitioner_id'],
        ['id'],
        ondelete='SET NULL',
    )
    op.create_foreign_key(
        'fk_calls_identified_patient_id_patients',
        'calls',
        'patients',
        ['identified_patient_id'],
        ['id'],
        ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_calls_identified_patient_id_patients', 'calls', type_='foreignkey')
    op.drop_constraint(
        'fk_calls_selected_practitioner_id_practitioners', 'calls', type_='foreignkey'
    )
    op.drop_constraint(
        'fk_calls_selected_appointment_type_id_appointment_types',
        'calls',
        type_='foreignkey',
    )
    op.drop_constraint('fk_calls_selected_branch_id_branches', 'calls', type_='foreignkey')
    op.drop_index(op.f('ix_calls_identified_patient_id'), table_name='calls')
    op.drop_column('calls', 'last_updated_at')
    op.drop_column('calls', 'last_tool_called')
    op.drop_column('calls', 'conversation_summary')
    op.drop_column('calls', 'pending_confirmation')
    op.drop_column('calls', 'last_availability_search')
    op.drop_column('calls', 'selected_appointment_type_id')
    op.drop_column('calls', 'selected_practitioner_id')
    op.drop_column('calls', 'selected_branch_id')
    op.drop_column('calls', 'identified_patient_id')
    op.drop_column('calls', 'current_intent')
    op.drop_column('calls', 'language')
    # ### end Alembic commands ###
