"""initial schema

Revision ID: a4a075a39043
Revises: 
Create Date: 2026-07-15 16:59:27.710212+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a4a075a39043'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # `btree_gist` adds GiST index support for equality on scalar types
    # (here, UUID). Required by the `uq_appointment_no_overlap` EXCLUDE
    # constraint on `appointments` below, which is what enforces
    # double-booking prevention at the database level. Not autogenerated
    # by Alembic -- SQLAlchemy's metadata has no concept of a Postgres
    # extension -- so it's added by hand, before the table that needs it.
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinics',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('default_timezone', sa.String(length=64), nullable=False),
    sa.Column('default_currency', sa.String(length=3), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patients',
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_phone'), 'patients', ['phone'], unique=False)
    op.create_table('branches',
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_branches_clinic_id'), 'branches', ['clinic_id'], unique=False)
    op.create_table('calls',
    sa.Column('retell_call_id', sa.String(length=128), nullable=True),
    sa.Column('patient_id', sa.UUID(), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('direction', sa.Enum('inbound', 'outbound', name='call_direction'), nullable=False),
    sa.Column('status', sa.Enum('in_progress', 'completed', 'disconnected', 'resumed', name='call_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('disconnected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resumed_from_call_id', sa.UUID(), nullable=True),
    sa.Column('detected_language_mix', sa.String(length=32), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resumed_from_call_id'], ['calls.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calls_patient_id'), 'calls', ['patient_id'], unique=False)
    op.create_index(op.f('ix_calls_phone'), 'calls', ['phone'], unique=False)
    op.create_index(op.f('ix_calls_retell_call_id'), 'calls', ['retell_call_id'], unique=True)
    op.create_table('departments',
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departments_clinic_id'), 'departments', ['clinic_id'], unique=False)
    op.create_table('appointment_types',
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('buffer_minutes', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('cancellation_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fee_window_hours', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointment_types_department_id'), 'appointment_types', ['department_id'], unique=False)
    op.create_table('call_turns',
    sa.Column('call_id', sa.UUID(), nullable=False),
    sa.Column('turn_index', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('caller', 'agent', 'system', name='turn_role'), nullable=False),
    sa.Column('language_detected', sa.String(length=16), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('tool_called', sa.String(length=64), nullable=True),
    sa.Column('asr_latency_ms', sa.Integer(), nullable=True),
    sa.Column('llm_ttft_ms', sa.Integer(), nullable=True),
    sa.Column('tool_latency_ms', sa.Integer(), nullable=True),
    sa.Column('tts_first_byte_ms', sa.Integer(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('call_id', 'turn_index', name='uq_call_turn_index')
    )
    op.create_index(op.f('ix_call_turns_call_id'), 'call_turns', ['call_id'], unique=False)
    op.create_table('followups',
    sa.Column('call_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=True),
    sa.Column('category', sa.Enum('human_requested', 'clinical_concern', 'other', name='followup_category'), nullable=False),
    sa.Column('status', sa.Enum('open', 'resolved', name='followup_status'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_followups_call_id'), 'followups', ['call_id'], unique=False)
    op.create_index(op.f('ix_followups_patient_id'), 'followups', ['patient_id'], unique=False)
    op.create_table('practitioners',
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_practitioners_clinic_id'), 'practitioners', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_practitioners_department_id'), 'practitioners', ['department_id'], unique=False)
    op.create_table('appointments',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('practitioner_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('appointment_type_id', sa.UUID(), nullable=False),
    sa.Column('created_by_call_id', sa.UUID(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('booked', 'rescheduled', 'cancelled', 'completed', 'no_show', name='appointment_status'), nullable=False),
    sa.Column('pms_sync_status', sa.Enum('pending', 'synced', 'failed', 'pending_retry', name='pms_sync_status'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    postgresql.ExcludeConstraint((sa.column('practitioner_id'), '='), (sa.text("tstzrange(start_time, end_time, '[)')"), '&&'), where=sa.text("status = 'booked'"), using='gist', name='uq_appointment_no_overlap'),
    sa.ForeignKeyConstraint(['appointment_type_id'], ['appointment_types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_call_id'], ['calls.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['practitioner_id'], ['practitioners.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_appointments_branch_start', 'appointments', ['branch_id', 'start_time'], unique=False)
    op.create_index(op.f('ix_appointments_patient_id'), 'appointments', ['patient_id'], unique=False)
    op.create_index('ix_appointments_practitioner_start', 'appointments', ['practitioner_id', 'start_time'], unique=False)
    op.create_table('practitioner_branches',
    sa.Column('practitioner_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['practitioner_id'], ['practitioners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('practitioner_id', 'branch_id', name='uq_practitioner_branch')
    )
    op.create_index(op.f('ix_practitioner_branches_branch_id'), 'practitioner_branches', ['branch_id'], unique=False)
    op.create_index(op.f('ix_practitioner_branches_practitioner_id'), 'practitioner_branches', ['practitioner_id'], unique=False)
    op.create_table('practitioner_schedules',
    sa.Column('practitioner_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('weekday', sa.Enum('monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday', name='weekday'), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['practitioner_id'], ['practitioners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_practitioner_schedules_branch_id'), 'practitioner_schedules', ['branch_id'], unique=False)
    op.create_index(op.f('ix_practitioner_schedules_practitioner_id'), 'practitioner_schedules', ['practitioner_id'], unique=False)
    op.create_table('idempotency_keys',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('operation_type', sa.Enum('create_appointment', 'reschedule_appointment', 'cancel_appointment', 'pms_write_back', name='idempotency_operation_type'), nullable=False),
    sa.Column('appointment_id', sa.UUID(), nullable=True),
    sa.Column('request_hash', sa.String(length=64), nullable=True),
    sa.Column('response_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_idempotency_keys_key'), 'idempotency_keys', ['key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_idempotency_keys_key'), table_name='idempotency_keys')
    op.drop_table('idempotency_keys')
    op.drop_index(op.f('ix_practitioner_schedules_practitioner_id'), table_name='practitioner_schedules')
    op.drop_index(op.f('ix_practitioner_schedules_branch_id'), table_name='practitioner_schedules')
    op.drop_table('practitioner_schedules')
    op.drop_index(op.f('ix_practitioner_branches_practitioner_id'), table_name='practitioner_branches')
    op.drop_index(op.f('ix_practitioner_branches_branch_id'), table_name='practitioner_branches')
    op.drop_table('practitioner_branches')
    op.drop_index('ix_appointments_practitioner_start', table_name='appointments')
    op.drop_index(op.f('ix_appointments_patient_id'), table_name='appointments')
    op.drop_index('ix_appointments_branch_start', table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_practitioners_department_id'), table_name='practitioners')
    op.drop_index(op.f('ix_practitioners_clinic_id'), table_name='practitioners')
    op.drop_table('practitioners')
    op.drop_index(op.f('ix_followups_patient_id'), table_name='followups')
    op.drop_index(op.f('ix_followups_call_id'), table_name='followups')
    op.drop_table('followups')
    op.drop_index(op.f('ix_call_turns_call_id'), table_name='call_turns')
    op.drop_table('call_turns')
    op.drop_index(op.f('ix_appointment_types_department_id'), table_name='appointment_types')
    op.drop_table('appointment_types')
    op.drop_index(op.f('ix_departments_clinic_id'), table_name='departments')
    op.drop_table('departments')
    op.drop_index(op.f('ix_calls_retell_call_id'), table_name='calls')
    op.drop_index(op.f('ix_calls_phone'), table_name='calls')
    op.drop_index(op.f('ix_calls_patient_id'), table_name='calls')
    op.drop_table('calls')
    op.drop_index(op.f('ix_branches_clinic_id'), table_name='branches')
    op.drop_table('branches')
    op.drop_index(op.f('ix_patients_phone'), table_name='patients')
    op.drop_table('patients')
    op.drop_table('clinics')
    # ### end Alembic commands ###

    # Left in place deliberately: dropping a shared Postgres extension
    # on downgrade is unsafe if anything else in the database (now or
    # later) also depends on it, and CREATE EXTENSION IF NOT EXISTS
    # above makes re-running upgrade() idempotent either way.
    # op.execute("DROP EXTENSION IF EXISTS btree_gist")
